// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWPrTgS5D0cMexf_vQAd772lCwA6D8kwQ',
    appId: '1:30101487917:web:786cfae94395fc376a93a4',
    messagingSenderId: '30101487917',
    projectId: 'naangarmapps',
    authDomain: 'naangarmapps.firebaseapp.com',
    storageBucket: 'naangarmapps.appspot.com',
    measurementId: 'G-MCCTPK2ENZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1MSJXKA5s-3dGrxEn7eYq1Vkqv88EvUQ',
    appId: '1:30101487917:android:ad9ca037f8a3f6476a93a4',
    messagingSenderId: '30101487917',
    projectId: 'naangarmapps',
    storageBucket: 'naangarmapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPkeNRdj36SelFpZF4u9OrBHc_tmicN2M',
    appId: '1:30101487917:ios:b9cad8e0c4ac36916a93a4',
    messagingSenderId: '30101487917',
    projectId: 'naangarmapps',
    storageBucket: 'naangarmapps.appspot.com',
    iosBundleId: 'com.sixamtech.naangarm',
  );

}